### PR TITLE
Use PSR 12 when linting

### PR DESCRIPTION
**Pull request by LeoColomb**
And apply it on every PHP filesin the repo

### CODE REVIEW

**Comment by austinpray** [comment]
I’ll leave PSR12 decision to @TangRufus, I don’t really care.

I definitely insist we do not run linting on our tests, that’s a bit much for me.

**Comment by TangRufus** [comment]
I vote for PSR12!

> I definitely insist we do not run linting on our tests

Agree.

**Comment by TangRufus** [comment]
Added some commits at https://github.com/LeoColomb/wordpress-packager/pull/2

Discuss: Do we allow phpcs warnings?
(the `n` on https://github.com/roots/wordpress-packager/blob/d40d43ac491f0043f74583f976e1cd3f1c2b5e89/phpcs.xml#L18)

**Comment by LeoColomb** [comment]
Merged.

> Do we allow phpcs warnings?

I vote to keep `n`! 😸

**Comment by TangRufus** [comment]
Looks good to me.

> Do we allow phpcs warnings?

We don't have any warnings anyway.

**Comment by austinpray** [comment]
Thank you!

**Comment by LeoColomb** [comment]
@TangRufus I'm thinking back to your suggestion: actually PSR-2 is deprecated, only PSR-12 should be used. 🙂

**Pull request merged**
