### PR TITLE
weekly composer update

### PR DESCRIPTION
**Pull request by austinpray**
live seems like lots of merge conflicts and lots of daily work keeping this up to date

### CODE REVIEW

**Comment by LeoColomb** [comment]
My little suggestion 😉 

```yaml
update_configs:
  - package_manager: php:composer
    directory: /
    update_schedule: live
    # allowed_updates: empty, by default only direct/top-level dependencies are kept up to date which is sufficient
    automerged_updates: # extra, to reduce work
      - match:
          dependency_type: "development"
          update_type: "all"
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
```

https://dependabot.com/docs/config-file/

**Comment by austinpray** [comment]
@LeoColomb I like your’s better, submit a PR!

**Comment by austinpray** [comment]
Nvm 

> Automerged updates is currently in closed beta, contact support@dependabot.com to enable it on your account.

can do this later

**Comment by LeoColomb** [comment]
Oh, just submitted my PR 😄 #36 

Where do you read this? I use automerge feature since almost 6 mounts without subscribing to any beta program...

**Comment by austinpray** [comment]
https://github.com/roots/wordpress-packager/issues/37

/shrug maybe they will enable it for us quickly

**Pull request merged**
