### PR TITLE
Add CircleCI config

### LINKED ISSUE #3: run tests on circleci
We have two test commands: 
- `composer test` <- default test suite 
- `composer test:e2e` <- end-to-end tests (none right now)

Can prolly just steal https://github.com/ItinerisLtd/wordpress-packager/blob/d56ca71f450349fb8e910e12be888cc392cc1aa1/.circleci/config.yml

@TangRufus wanna do this since you are already a pro at circleci?

### PR DESCRIPTION
**Pull request by TangRufus**
Close #3

### CODE REVIEW

**Comment by TangRufus** [comment]
@austinpray needs an admin to enable this repo on CircleCI

**Comment by austinpray** [comment]
Closing https://github.com/roots/wordpress-packager/pull/8 in favor of this.

Merge https://github.com/roots/wordpress-packager/tree/4-docker-codecov with this branch and just delete my branch's circleci config?

**Comment by TangRufus** [comment]
@austinpray Can you set `CC_TEST_REPORTER_ID` on circleci?

What is the use of Docker?

**Comment by austinpray** [comment]
@TangRufus CC_TEST_REPORTER_ID is set already

**Comment by austinpray** [comment]
@TangRufus oh that env variable is missing cause its a fork

**Comment by austinpray** [comment]
close in favor of #9

**Pull request closed without merging**
