### PR TITLE
refactor: fix codeclimate issues

### PR DESCRIPTION
**Pull request by atymic**
Let me know if you have any suggestions/other changes :smile: 

- Simplify `isValidReleaseURL()` to remove excess returns
- Refactor `getRepo()` to reduce complexity
- Reduce `WordPressPackage` constructor length by splitting string out into constants
- Fix style issues

Relates to #17, #19

### CODE REVIEW

**Comment by atymic** [comment]
Oops, just realised there was a PR up that makes some large changes.
https://github.com/roots/wordpress-packager/pull/33
I'll wait until that's merged and then jump on any required fixes after :)

**Comment by austinpray** [comment]
Can incorporate some of your changes into my branch, thanks!

**Comment by austinpray** [comment]
I went with splitting these into methods rather than adding a bunch of constants to the public api. Thanks for the PR though!

**Comment by atymic** [comment]
No worries :)
Should have checked first.

**Pull request closed without merging**
